# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0641016614659ae379a08120c1c875ba589e86dcd08767665f1678247fc06b4efd9958a6d1064d669dcd75fabad4d959faf66d3f7951bcbac3667d69c01cc062

test:
  secret_key_base: cb859873b9712393a5281b6453a7722ba4410f017841c3161be10c4622a153887488ddc8611f99a6e0e6fdc5536405a834ed0e1a54c7dd51e685b1bef291cfda

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
